apiVersion: v1 #kubernetes Api version
kind: Service #kuberneter kind which type we are creating
metadata: #metadat of resource kind that we are creating
  name: congestion-tax-calculator-docker
spec:
  selector:
    app: congestion-tax-calculator-docker
  ports:
    - protocol: "TCP"
      port: 8081 #port that a resource is running on a cluster
      targetPort: 8081 #port exposed by the service
  type: LoadBalancer #type of service. Loadbalancer shows that our service will be external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: congestion-tax-calculator-docker
spec:
  selector:
    matchLabels:
      app: congestion-tax-calculator-docker
  replicas: 2 #number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: congestion-tax-calculator-docker
    spec:
      containers:
        - name: congestion-tax-calculator-docker
          image: congestion-tax-calculator-docker #images that will be used to container in the cluster
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 8081

